"Public API"

load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "paq",
    srcs = ["src/bin.rs"],
    deps = [
        # List your crate's dependencies here
    ],
    edition = "2018",
)